# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-23 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20180215_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='ip_address',
            field=models.CharField(default='', max_length=20),
        ),
    ]
