# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-15 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='thumbs_down',
            field=models.PositiveIntegerField(default=0, verbose_name='踩'),
        ),
        migrations.AddField(
            model_name='comment',
            name='thumbs_up',
            field=models.PositiveIntegerField(default=0, verbose_name='赞'),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
