# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-22 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_stockrecoder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockrecoder',
            name='time',
            field=models.CharField(default='', max_length=20, verbose_name='时间'),
        ),
    ]
