# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-22 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180222_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockrecoder',
            name='content',
            field=models.TextField(default='', verbose_name='内容'),
        ),
    ]
