# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-22 11:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180222_1901'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StockRecoder',
            new_name='StockRecorder',
        ),
    ]
