# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-18 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180222_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='modify_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='最新修改'),
        ),
    ]
